# Generated by Django 4.0.2 on 2022-03-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_userprofile_user_userprofile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
