# Generated by Django 4.0.2 on 2022-03-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('birthYear', models.IntegerField()),
                ('deathYear', models.IntegerField()),
                ('movie1', models.CharField(max_length=100)),
                ('movie2', models.CharField(max_length=100)),
                ('movie3', models.CharField(max_length=100)),
                ('movie4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('imageUrl', models.URLField()),
                ('director', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('genre1', models.CharField(max_length=20, null=True)),
                ('genre2', models.CharField(max_length=20, null=True)),
                ('plot', models.CharField(max_length=10000, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('votes', models.IntegerField(null=True)),
                ('runtime', models.CharField(max_length=3, null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
    ]
