# Generated by Django 4.0.2 on 2022-03-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('birthYear', models.IntegerField()),
                ('deathYear', models.IntegerField()),
                ('movie1', models.CharField(max_length=100)),
                ('movie2', models.CharField(max_length=100)),
                ('movie3', models.CharField(max_length=100)),
                ('movie4', models.CharField(max_length=100)),
            ],
        ),
    ]
