# Generated by Django 4.0.2 on 2022-03-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
    ]
