# Generated by Django 4.0.2 on 2022-03-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_director_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='releaseDate',
            field=models.CharField(max_length=100),
        ),
    ]
