# Generated by Django 4.0.2 on 2022-03-22 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_plot_alter_movie_releasedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='birthYear',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='deathYear',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='movie1',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='movie2',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='movie3',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='movie4',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movie.movie'),
        ),
    ]
