# Generated by Django 4.0.2 on 2022-03-22 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_actor_birthyear_remove_actor_deathyear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='id',
            new_name='movieId',
        ),
    ]
