# Generated by Django 4.0.2 on 2022-03-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_rename_id_actor_movieid'),
    ]

    operations = [
        migrations.CreateModel(
            name='topmovie',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
    ]
