# Generated by Django 4.0.2 on 2022-03-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_topmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmovie',
            name='topId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movie.movie', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topmovie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
