# Generated by Django 4.0.2 on 2022-03-25 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_topmovie_topid_alter_topmovie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmovie',
            name='topId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
    ]
