# Generated by Django 4.0.2 on 2022-04-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_remove_profile_user_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('ordered_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending')], default=('P', 'Pending'), max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
