# Generated by Django 4.0.1 on 2022-04-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
