# Generated by Django 4.0.1 on 2022-04-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_order_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertoken',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('requested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending')], default='P', max_length=2),
        ),
    ]
