# Generated by Django 4.0.2 on 2022-04-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_order_status_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertoken',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('requested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
