# Generated by Django 4.0.1 on 2022-04-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_usertoken_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
