# Generated by Django 4.0.2 on 2022-04-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
